version: '3'

services:
  web:
    build: .
    command: python MyProject/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=yhljatit
      - POSTGRES_USER=yhljatit
      - POSTGRES_PASSWORD=0TEdmRd_rarPdBJkjt1XHATA1_w7Gr0N
  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    image: celery:latest
    command: celery -A MyProject worker -l INFO
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - db
      - redis
