# Generated by Django 3.1.5 on 2021-01-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mechtasmartphones_mechtasmartphoneshistory_shopekzsmartphones_shopekzsmartphoneshistory_technodomsma'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopeKzSmartphones',
            new_name='ShopKzSmartphones',
        ),
        migrations.RenameModel(
            old_name='ShopeKzSmartphonesHistory',
            new_name='ShopKzSmartphonesHistory',
        ),
    ]
