# Generated by Django 3.1.5 on 2021-01-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210111_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='sulpaksmartphones',
            name='image_file',
            field=models.ImageField(default=-1.0, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sulpaksmartphones',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechtasmartphones',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mechtasmartphoneshistory',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopkzsmartphones',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shopkzsmartphoneshistory',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sulpaksmartphones',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sulpaksmartphoneshistory',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='technodomsmartphones',
            name='current_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='technodomsmartphoneshistory',
            name='price',
            field=models.IntegerField(),
        ),
    ]
