# Generated by Django 3.1.5 on 2021-01-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210119_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sulpaksmartphones',
            name='image_file',
        ),
    ]
