# Generated by Django 3.1.5 on 2021-01-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_sulpaksmartphones_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SulpakCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakHeadphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakPowerbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakTablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakVRglass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('current_price', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SulpakWatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakVRglassHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakTVHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakTabletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakPrinterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakPowerbankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakMonitorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakHeadphoneHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
        migrations.CreateModel(
            name='SulpakCameraHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaksmartphones')),
            ],
        ),
    ]
