# Generated by Django 3.1.5 on 2021-01-19 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sulpakcamera_sulpakcamerahistory_sulpakheadphone_sulpakheadphonehistory_sulpakmonitor_sulpakmonitorh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sulpakcamerahistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakcamera'),
        ),
        migrations.AlterField(
            model_name='sulpakheadphonehistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakheadphone'),
        ),
        migrations.AlterField(
            model_name='sulpakmonitorhistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakmonitor'),
        ),
        migrations.AlterField(
            model_name='sulpakpowerbankhistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakpowerbank'),
        ),
        migrations.AlterField(
            model_name='sulpakprinterhistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakprinter'),
        ),
        migrations.AlterField(
            model_name='sulpaktablethistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaktablet'),
        ),
        migrations.AlterField(
            model_name='sulpaktvhistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpaktv'),
        ),
        migrations.AlterField(
            model_name='sulpakvrglasshistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakvrglass'),
        ),
        migrations.AlterField(
            model_name='sulpakwatchhistory',
            name='phone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sulpakwatch'),
        ),
    ]
