# Generated by Django 3.1.5 on 2021-01-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210120_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sulpakcamera',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpakheadphone',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpakmonitor',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpakpowerbank',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpakprinter',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpaksmartphones',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpaktablet',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpaktv',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpakvrglass',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='sulpakwatch',
            name='image_url',
        ),
    ]
