# Generated by Django 3.1.5 on 2021-01-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_printer_smartphone_tablet_tv_vrglass_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphone',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='headphone',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphone',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='headphone',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='headphone',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='headphone',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='monitor',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='monitor',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='monitor',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='powerbank',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='printer',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='printer',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printer',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='printer',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tablet',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tablet',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tablet',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tablet',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tv',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tv',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tv',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tv',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vrglass',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='vrglass',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vrglass',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='vrglass',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vrglass',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='vrglass',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='shopkz_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='watch',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='sulpak_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='watch',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='technodom_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='watch',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
