# Generated by Django 3.1.5 on 2021-01-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210122_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='shopkz_name',
            field=models.CharField(default='Null', max_length=500),
        ),
    ]
