# Generated by Django 3.1.5 on 2021-01-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210122_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='shopkz_name',
        ),
    ]
