# Generated by Django 3.1.5 on 2021-01-22 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_monitor_shopkz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='shopkz_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
