# Generated by Django 3.1.5 on 2021-01-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_monitor_shopkz_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='shopkz_name',
        ),
    ]
