# Generated by Django 3.1.5 on 2021-01-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210122_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='shopkz_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='shopkz_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='sulpak_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='sulpak_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='technodom_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='camera',
            name='technodom_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
